PRIMARY = "#0078D4"
PRIMARY_HOVER = "#106EBE"
PRIMARY_LIGHT = "#E8F4FD"
DANGER = "#E63946"
WARNING = "#F4A261"
SUCCESS = "#2ECC71"
INFO = "#3498DB"
BG_PAGE = "#F0F2F5"
BG_WHITE = "#FFFFFF"
BG_CARD = "#FAFAFA"
BG_HOVER = "#F0F0F0"
SIDEBAR_BG = "#F8F9FA"
TEXT_PRIMARY = "#1A1A1A"
TEXT_SECONDARY = "#666666"
TEXT_TERTIARY = "#999999"
BORDER = "#E0E0E0"
BORDER_LIGHT = "#EBEBEB"
SHADOW = "#0000000A"
FONT_FAMILY = "Microsoft YaHei UI"
FONT_SIZE_XS = 11
FONT_SIZE_SMALL = 12
FONT_SIZE_NORMAL = 13
FONT_SIZE_LARGE = 15
FONT_SIZE_XL = 18
PADDING_SMALL = 4
PADDING_NORMAL = 8
PADDING_LARGE = 16
PADDING_XL = 24
GRID_SIZE = 8
RISK_COLORS = {
    "致命": DANGER,
    "高危": WARNING,
    "人工复核": INFO,
    "合规": SUCCESS,
}
SLOT_NAMES = ["招标文件", "商务标", "技术标", "价格标"]
SLOT_ICONS = ["📄", "📋", "🔧", "💰"]
